"""Initial migration

Revision ID: d9178442809e
Revises: 
Create Date: 2025-11-22 06:41:22.277650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9178442809e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('peso', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('palabras_clave', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_criterios_codigo', 'criterios', ['codigo'], unique=True)
    op.create_table('hoteles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), server_default='Barranquilla', nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sitio_web', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hoteles_ciudad', 'hoteles', ['ciudad'], unique=False)
    op.create_index('ix_hoteles_nombre', 'hoteles', ['nombre'], unique=False)
    op.create_table('plataformas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_base', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_plataformas_codigo', 'plataformas', ['codigo'], unique=True)
    op.create_table('hotel_plataforma',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('plataforma_id', sa.UUID(), nullable=False),
    sa.Column('url_hotel', sa.Text(), nullable=True),
    sa.Column('identificador_externo', sa.String(length=255), nullable=True),
    sa.Column('ultimo_scraping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_resenas_extraidas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'plataforma_id', name='uq_hotel_plataforma')
    )
    op.create_index('ix_hotel_plataforma_hotel', 'hotel_plataforma', ['hotel_id'], unique=False)
    op.create_index('ix_hotel_plataforma_plataforma', 'hotel_plataforma', ['plataforma_id'], unique=False)
    op.create_table('indicadores_periodo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_resenas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('promedio_sostenibilidad', sa.Float(), nullable=True),
    sa.Column('promedio_calidad', sa.Float(), nullable=True),
    sa.Column('promedio_general', sa.Float(), nullable=True),
    sa.Column('total_positivas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_negativas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_neutras', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('calculado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'periodo_inicio', 'periodo_fin', name='uq_hotel_periodo')
    )
    op.create_index('ix_indicadores_hotel', 'indicadores_periodo', ['hotel_id'], unique=False)
    op.create_index('ix_indicadores_periodo', 'indicadores_periodo', ['periodo_inicio', 'periodo_fin'], unique=False)
    op.create_table('resenas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_plataforma_id', sa.UUID(), nullable=False),
    sa.Column('nombre_autor', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_autor', sa.String(length=255), nullable=True),
    sa.Column('texto_positivo', sa.Text(), nullable=True),
    sa.Column('texto_negativo', sa.Text(), nullable=True),
    sa.Column('texto_completo', sa.Text(), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_estadia', sa.String(length=100), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('procesada', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('fecha_procesamiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_plataforma_id'], ['hotel_plataforma.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resenas_fecha_publicacion', 'resenas', ['fecha_publicacion'], unique=False)
    op.create_index('ix_resenas_hash', 'resenas', ['hash_contenido'], unique=False)
    op.create_index(op.f('ix_resenas_hash_contenido'), 'resenas', ['hash_contenido'], unique=False)
    op.create_index('ix_resenas_hotel_plataforma', 'resenas', ['hotel_plataforma_id'], unique=False)
    op.create_index('ix_resenas_procesada', 'resenas', ['procesada'], unique=False)
    op.create_index('ix_resenas_puntuacion', 'resenas', ['puntuacion'], unique=False)
    op.create_table('clasificaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resena_id', sa.UUID(), nullable=False),
    sa.Column('criterio_id', sa.UUID(), nullable=False),
    sa.Column('valoracion', sa.Float(), nullable=False),
    sa.Column('confianza', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('palabras_detectadas', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('procesado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resena_id'], ['resenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resena_id', 'criterio_id', name='uq_resena_criterio')
    )
    op.create_index('ix_clasificaciones_criterio', 'clasificaciones', ['criterio_id'], unique=False)
    op.create_index('ix_clasificaciones_resena', 'clasificaciones', ['resena_id'], unique=False)
    op.create_index('ix_clasificaciones_valoracion', 'clasificaciones', ['valoracion'], unique=False)
    op.create_table('resenas_destacadas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('resena_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resena_id'], ['resenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resenas_destacadas_hotel', 'resenas_destacadas', ['hotel_id'], unique=False)
    op.create_index('ix_resenas_destacadas_tipo', 'resenas_destacadas', ['tipo'], unique=False)
    op.create_table('sentimientos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('resena_id', sa.UUID(), nullable=False),
    sa.Column('tipo_sentimiento', sa.String(length=20), nullable=False),
    sa.Column('score_positivo', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('score_negativo', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('score_neutro', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('score_compuesto', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('confianza', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resena_id'], ['resenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resena_id')
    )
    op.create_index('ix_sentimientos_resena', 'sentimientos', ['resena_id'], unique=True)
    op.create_index('ix_sentimientos_tipo', 'sentimientos', ['tipo_sentimiento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentimientos_tipo', table_name='sentimientos')
    op.drop_index('ix_sentimientos_resena', table_name='sentimientos')
    op.drop_table('sentimientos')
    op.drop_index('ix_resenas_destacadas_tipo', table_name='resenas_destacadas')
    op.drop_index('ix_resenas_destacadas_hotel', table_name='resenas_destacadas')
    op.drop_table('resenas_destacadas')
    op.drop_index('ix_clasificaciones_valoracion', table_name='clasificaciones')
    op.drop_index('ix_clasificaciones_resena', table_name='clasificaciones')
    op.drop_index('ix_clasificaciones_criterio', table_name='clasificaciones')
    op.drop_table('clasificaciones')
    op.drop_index('ix_resenas_puntuacion', table_name='resenas')
    op.drop_index('ix_resenas_procesada', table_name='resenas')
    op.drop_index('ix_resenas_hotel_plataforma', table_name='resenas')
    op.drop_index(op.f('ix_resenas_hash_contenido'), table_name='resenas')
    op.drop_index('ix_resenas_hash', table_name='resenas')
    op.drop_index('ix_resenas_fecha_publicacion', table_name='resenas')
    op.drop_table('resenas')
    op.drop_index('ix_indicadores_periodo', table_name='indicadores_periodo')
    op.drop_index('ix_indicadores_hotel', table_name='indicadores_periodo')
    op.drop_table('indicadores_periodo')
    op.drop_index('ix_hotel_plataforma_plataforma', table_name='hotel_plataforma')
    op.drop_index('ix_hotel_plataforma_hotel', table_name='hotel_plataforma')
    op.drop_table('hotel_plataforma')
    op.drop_index('ix_plataformas_codigo', table_name='plataformas')
    op.drop_table('plataformas')
    op.drop_index('ix_hoteles_nombre', table_name='hoteles')
    op.drop_index('ix_hoteles_ciudad', table_name='hoteles')
    op.drop_table('hoteles')
    op.drop_index('ix_criterios_codigo', table_name='criterios')
    op.drop_table('criterios')
    # ### end Alembic commands ###
